# Generated by Django 4.2.9 on 2024-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_order_cu_name_order_cu_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=350),
        ),
    ]
