# Generated by Django 4.2.13 on 2024-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_parameter_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrequest',
            options={'verbose_name': 'Запрос уведомления', 'verbose_name_plural': 'Запросы уведомления'},
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='link',
            field=models.URLField(default='', max_length=512),
        ),
    ]
