# Generated by Django 4.2.9 on 2024-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_product_actual_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='format',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
