# Generated by Django 4.2.13 on 2024-06-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_notificationrequest_options_aboutitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablesize',
            name='order_value',
            field=models.IntegerField(default=0),
        ),
    ]
