# Generated by Django 4.2.13 on 2024-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_availablesize_order_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablesize',
            options={'ordering': ['order_value'], 'verbose_name': 'Доступный размер', 'verbose_name_plural': 'Доступные размеры'},
        ),
        migrations.AddField(
            model_name='notificationrequest',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
