# Generated by Django 4.2.13 on 2024-07-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_order_delivery_order_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_supplements_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
