# Generated by Django 4.2.13 on 2024-07-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_order_delivery_supplements_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cu_apartment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cu_entrance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cu_floor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
