# Generated by Django 4.2.9 on 2024-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_notificationrequest_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
