# Generated by Django 4.2.9 on 2024-01-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_param_alter_availablesize_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Param',
            new_name='Parameter',
        ),
    ]
