# Generated by Django 4.2.9 on 2024-01-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_rename_param_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='Описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='Имя',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='Значение',
            new_name='value',
        ),
    ]
