# Generated by Django 4.2.9 on 2024-01-28 19:09

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_rename_описание_parameter_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablesize',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='availablesize',
            name='unique_size_per_product',
        ),
        migrations.AlterField(
            model_name='availablesize',
            name='size',
            field=models.CharField(max_length=30),
        ),
    ]
