# Generated by Django 4.2.9 on 2024-01-28 19:24

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_availablesize_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablesize',
            options={'ordering': ['size']},
        ),
        migrations.AlterField(
            model_name='availablesize',
            name='size',
            field=models.CharField(max_length=30, validators=[lms.models.Tunable.validate_size]),
        ),
        migrations.AddConstraint(
            model_name='availablesize',
            constraint=models.UniqueConstraint(fields=('size', 'product_id'), name='unique_size_per_product'),
        ),
    ]
