# Generated by Django 4.2.9 on 2024-01-29 18:09

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_parameter_in_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[lms.models.Tunable.validate_article]),
        ),
    ]
