# Generated by Django 4.2.9 on 2024-01-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_alter_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cu_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='cu_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cu_phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
