# Generated by Django 4.2.9 on 2024-01-31 15:50

import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_alter_availablesize_quantity_alter_category_kind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_service',
        ),
        migrations.AddField(
            model_name='order',
            name='bank_payment_id',
            field=models.CharField(default='unk', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUR', max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='RUR', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
