# Generated by Django 4.2.9 on 2024-01-31 16:13

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_rename_delivery_order_delivery_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='phone',
            field=models.CharField(max_length=50, null=True, validators=[lms.models.Tunable.validate_phone]),
        ),
        migrations.AlterField(
            model_name='order',
            name='cu_phone',
            field=models.CharField(max_length=50, null=True, validators=[lms.models.Tunable.validate_phone]),
        ),
    ]
