# Generated by Django 4.2.9 on 2024-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_alter_notificationrequest_phone_alter_order_cu_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cu_entrance',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
