# Generated by Django 4.2.9 on 2024-02-07 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_order_cu_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.BigIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(choices=[('cd', 'СДЭК'), ('pr', 'Почта России')], default='cd', max_length=2),
        ),
    ]
