# Generated by Django 4.2.9 on 2024-02-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_collaborator_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborator',
            new_name='Coworker',
        ),
    ]
