# Generated by Django 4.2.9 on 2024-02-08 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_rename_collaborator_coworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region_code', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='RU', max_length=2)),
                ('country', models.CharField(default='Россия', max_length=50)),
            ],
            options={
                'ordering': ['region'],
                'indexes': [models.Index(fields=['region'], name='lms_region_region_505c43_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.BigIntegerField(editable=False)),
                ('city', models.CharField(max_length=100)),
                ('sub_region', models.CharField(max_length=100)),
                ('longitude', models.FloatField(editable=False)),
                ('latitude', models.FloatField(editable=False)),
                ('time_zone', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='lms.region')),
            ],
            options={
                'ordering': ['city'],
                'indexes': [models.Index(fields=['city', 'code'], name='lms_city_city_a3e59d_idx')],
            },
        ),
    ]
