# Generated by Django 4.2.9 on 2024-02-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_region_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='sub_region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
