# Generated by Django 4.2.9 on 2024-02-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_alter_city_sub_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='Россия', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(default='RU', max_length=2),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='lms.region'),
        ),
    ]
