# Generated by Django 4.2.9 on 2024-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_city_country_city_country_code_alter_city_region'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='lms_city_city_a3e59d_idx',
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['city', 'code', 'city_uuid'], name='lms_city_city_19f7a8_idx'),
        ),
    ]
