# Generated by Django 4.2.9 on 2024-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_remove_city_lms_city_city_a3e59d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_lc',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
