# Generated by Django 4.2.9 on 2024-02-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_remove_city_lms_city_city_19f7a8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cu_country',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(default=1021, on_delete=django.db.models.deletion.PROTECT, to='lms.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cu_city_region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cu_city_subregion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cu_city_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
