# Generated by Django 4.2.9 on 2024-02-09 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0038_remove_order_cu_country_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
