# Generated by Django 4.2.9 on 2024-02-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0039_orderitem_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
