# Generated by Django 4.2.9 on 2024-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0042_alter_order_bank_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cu_country',
            field=models.CharField(default='RU', max_length=2),
        ),
    ]
