# Generated by Django 4.2.9 on 2024-02-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0043_order_cu_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank_payment_id',
            field=models.UUIDField(null=True),
        ),
    ]
