# Generated by Django 4.2.9 on 2024-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0045_setting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=32),
        ),
    ]
