# Generated by Django 4.2.9 on 2024-02-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0046_alter_setting_id_alter_setting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
