# Generated by Django 4.2.9 on 2024-02-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0047_alter_setting_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['key']},
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('key', 'owner_id'), name='unique_key_per_owner'),
        ),
    ]
