# Generated by Django 4.2.9 on 2024-02-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0048_alter_setting_options_setting_unique_key_per_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['key'], name='lms_setting_key_cb6094_idx'),
        ),
    ]
