# Generated by Django 4.2.9 on 2024-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0049_setting_lms_setting_key_cb6094_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bank_payment_id',
            new_name='payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Открыт, но не оплачен'), (1, 'Открыт и оплачен'), (2, 'Выполнен и закрыт')], default=0),
        ),
    ]
