# Generated by Django 4.2.9 on 2024-02-14 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0050_rename_bank_payment_id_order_payment_id_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='brand/%Y/%m/%d')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('kind', models.IntegerField(choices=[(0, 'Выбрал нас'), (1, 'Партнёр')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
