# Generated by Django 4.2.9 on 2024-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0051_aboutitem_alter_order_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='closed_at',
            new_name='completed_at',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'Платёж провален'), (3, 'Выполнен')], default=0),
        ),
    ]
