# Generated by Django 4.2.9 on 2024-02-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0052_rename_closed_at_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availablesize',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_positive'),
        ),
    ]
