services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./lmshop:/code
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    command: gunicorn --bind=web:8000 lmshop.wsgi
    restart: always
    volumes:
      - ./lmshop:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=lmshop.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

